### ISSUE TITLE
Implement the Text to Text API from any language to any language using Watson  

### ISSUE THREAD

**Issue by sharathk91** [sharathk91/Team10ASEProject#2]

**Comment by sheriaravind** [comment]
Worked on the issue and below are the steps involved in the completing the text to text language conversion.
1. Created a IBM Watson text to text conversion API key to use in the project for conversion of text to text from any language to any language.
2. Created two text fields for user to enter the text to convert and the other to print the converted or translated text.
3. Created two drop down language list so that user can select the source language and the language he wanted to translate.
4. Used IBM Watson API and passed the user text for the translation.
5. Tested the application and the application is working fine.
