### ISSUE TITLE
Implement Registeration page to store user details in Local storage of browser

### ISSUE THREAD

**Issue by sharathk91** [sharathk91/Team10ASEProject#6]

**Comment by sheriaravind** [comment]
Created a Registration page so that user can register and use the various services included in the application. Below are the steps involved.
1. Created various fields that are to be filled by the user for the registration.
2. Performed various checks for the details entered by the user using java script so that the load on the server is low.
3.  Used browser local memory for the registration and every time user logins the user details are fetched from the browser local memory.
4. Tested the functionality and everything is working fine.
